require('plugins')
require('sets')
require('globals')
require('keymappings')
require('set-treesitter')
require('set-compe')
require('set-telescope')
require('set-comment')
require('set-gitsigns')
require('set-nvim-tree')

-- LSP
require('lsp')
-- require('lsp.js-ts')
require('colorscheme')
